import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#050505",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  centered: {
    flex: 1,
    backgroundColor: "#050505",
    alignItems: "center",
    justifyContent: "center",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
  },
  brand: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    marginRight: 12,
    backgroundColor: "#1a1a1a",
    borderWidth: 1,
    borderColor: "#232323",
    alignItems: "center",
    justifyContent: "center",
  },
  brandImage: {
    width: "100%",
    height: "100%",
  },
  brandPlaceholder: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  brandInitials: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  brandLevelBadge: {
    position: "absolute",
   bottom: -6,
   alignSelf: "center",
    backgroundColor: "#ff7a1a",
    paddingHorizontal: 8,
    paddingVertical: 2,
   borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2a2a2a",
  },
  brandLevelText: {
    color: "#1a1a1a",
    fontSize: 10,
    fontWeight: "700",
  },
  brandName: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "600",
    // removed flex:1 here to allow the smallMuted line to render
  },
  smallMuted: {
    color: "#9a9a9a",
    fontSize: 13,
    marginTop: 4,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#101010",
    borderWidth: 1,
    borderColor: "#2a2a2a",
  },
  greetingSection: {
    marginTop: 18,
  },
  greetingTitle: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "700",
  },
  wave: {
    fontSize: 24,
  },
  greetingSubtitle: {
    color: "#9a9a9a",
    fontSize: 15,
    marginTop: 6,
  },
  card: {
    backgroundColor: "#121212",
    borderRadius: 16,
    padding: 14,
    marginTop: 18,
    borderWidth: 1,
    borderColor: "#1f1f1f",
  },
  cardRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  cardTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  cardMeta: {
    color: "#8a8a8a",
    fontSize: 13,
    marginTop: 4,
  },
  sectionTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 12,
  },
  startButton: {
    backgroundColor: "#ff7a1a",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginLeft: 12,
  },
  startButtonText: {
    color: "#1a1a1a",
    fontWeight: "700",
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  activityIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#181818",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  activityText: {
    color: "#f0f0f0",
    fontSize: 14,
    fontWeight: "500",
  },
  activityDay: {
    color: "#7a7a7a",
    fontSize: 12,
    marginTop: 4,
  },
  ctaButton: {
    marginTop: 22,
    backgroundColor: "#ff7a1a",
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ff7a1a",
    shadowOpacity: 0.4,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  ctaButtonText: {
    color: "#1a1a1a",
    fontSize: 16,
    fontWeight: "700",
  },
});